### ISSUE TITLE
[BUG] ODTP installation is FINISHED, but odtp --help gives an error

### ISSUE THREAD

**Issue by vodor001** [odtp-org/odtp#115]
## Environment

- **ODTP/ODTP Component version:** Which version are you using?
0.2.0
- **Operating System:** Include operating system where you are running the tool.
Windows 10

## Bug description
After the full installation, odtp –help throws an error regarding MONGO_SERVER
 
Installing the current project: odtp (0.2.0)
 
(odtp-py3.11) C:\Users\vodor001\Documents\ODTP\odtp-main\odtp-main>odtp --help
Traceback (most recent call last):
  File "C:\Users\vodor001\AppData\Local\pypoetry\Cache\virtualenvs\odtp-cDzXzc4r-py3.11\Scripts\\odtp", line 3, in <module>
    from odtp.cli.main import app
  File "C:\Users\vodor001\Documents\ODTP\odtp-main\odtp-main\odtp\cli\main.py", line 12, in <module>
    from odtp.helpers.utils import get_odtp_version
  File "C:\Users\vodor001\Documents\ODTP\odtp-main\odtp-main\odtp\helpers\utils.py", line 3, in <module>
    import odtp.mongodb.db as db
  File "C:\Users\vodor001\Documents\ODTP\odtp-main\odtp-main\odtp\mongodb\db.py", line 11, in <module>
    import odtp.helpers.git as git_helpers
  File "C:\Users\vodor001\Documents\ODTP\odtp-main\odtp-main\odtp\helpers\git.py", line 6, in <module>
    from odtp.helpers.settings import GITHUB_TOKEN
  File "C:\Users\vodor001\Documents\ODTP\odtp-main\odtp-main\odtp\helpers\settings.py", line 8, in <module>
    ODTP_MONGO_SERVER = odtp_config["ODTP_MONGO_SERVER"]
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ODTP_MONGO_SERVER'
(odtp-py3.11) C:\Users\vodor001\Documents\ODTP\odtp-main\odtp-main>


### Additional info
`echo $ODTP_MONGO_SERVER` command gives me $ODTP_MONGO_SERVER, which makes me guess that probably the variable was not defined. However, I have configured the env.dist file aproproately, so that 
ODTP_MONGO_SERVER=mongodb://[MY_USERNAME]:[MY_PASSWORD]@[MY_IP]/

**Comment by sabinem** [comment]
@vodor001 Closing the bug as the version is outdated. Please try with the latest version. And sorry for not seeing and replying to this earlier.
