### ISSUE TITLE
Boolean object definition

### ISSUE THREAD

**Issue by peiling24** [odtp-org/odtp#178]
## Environment

**ODTP/ODTP Component version:0.2.8
**Operating System: Microsoft Windows 10 Education
### Summary:
In step 7 with command docker exec -it odtp-odtp-1 odtp setup initiate, this error showed up:

INFO (18/06/2024 08:39:22 AM): environment variables loaded (LineL 6 [settings.py])
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/odtp/helpers/settings.py", line 22, in <module>
    ODTP_DASHBOARD_RELOAD = eval(os.getenv("ODTP_DASHBOARD_RELOAD"))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'FALSE' is not defined. Did you mean: 'False'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/odtp", line 5, in <module>
    from odtp.cli.main import app
  File "/usr/local/lib/python3.11/site-packages/odtp/cli/main.py", line 12, in <module>
    from odtp.helpers.utils import get_odtp_version
  File "/usr/local/lib/python3.11/site-packages/odtp/helpers/utils.py", line 3, in <module>
    import odtp.mongodb.db as db
  File "/usr/local/lib/python3.11/site-packages/odtp/mongodb/db.py", line 11, in <module>
    import odtp.helpers.git as git_helpers
  File "/usr/local/lib/python3.11/site-packages/odtp/helpers/git.py", line 7, in <module>
    from odtp.helpers.settings import GITHUB_TOKEN
  File "/usr/local/lib/python3.11/site-packages/odtp/helpers/settings.py", line 25, in <module>
    raise OdtpSettingsException(f"Configuration of ODTP raised an exception {e}")
odtp.helpers.settings.OdtpSettingsException: Configuration of ODTP raised an exception name 'FALSE' is not defined

### Steps to reproduce the bug:
1.Follow [tutorial](https://odtp-org.github.io/odtp-manuals/installation/docker-compose_install/) on ubuntu until step 7

**Comment by peiling24** [comment]
It was resolved by changing the Boolean definition in .env file as

# Dashboard parameters
ODTP_DASHBOARD_PORT=8003
ODTP_DASHBOARD_RELOAD=False

**Comment by sabinem** [comment]
@peiling24 
Glad you could resolve this yourself. So I will close this issue.
